---
title: "msc dissertation"
author: "Halleyson Li"
date: "'r Sys.Date()'"
output: html_document
line-citations: apalike
linkcolor: blue
frontsize: 12pt
---

\newpage

# *Notes*{-}
1. The GitHub repository for this project could access through [here](https://github.com/halleyson/msc-dissertation.git)

# Loading data

```{r, message=FALSE}

library(readr)

pennycook1 <- read_csv("Pennycook et al._Study 1.csv")
pennycook2 <- read_csv("Pennycook et al._Study 2.csv")
# Quick check
head(pennycook2)

```

# General steps to regenerate headline result (study 2)
## data cleaning

```{r, message=FALSE}

# rename columns that contains special characters
colnames(pennycook2)
names(pennycook2)[1] <- "condition"

#conclude a sheet with only the relevant information 
#condition 1 = control; condition 2 = treatment 

#Choose with the column position 
library("dplyr")
pennystudy2r1 <- pennycook2 %>% 
  select (c(1, 2, 3, 4, 57, 60, 250, 252, 284))

#re-code sharing intentions (fake/real) using the scale midpoint (1-3 = 0, 4-6 = 1)
pennystudy2r1$Fake[pennystudy2r1$Fake > 0 & pennystudy2r1$Fake < 4] <- 0
pennystudy2r1$Fake[pennystudy2r1$Fake > 3 & pennystudy2r1$Fake < 7] <- 1
pennystudy2r1$Fake

pennystudy2r1$Real[pennystudy2r1$Real > 0 & pennystudy2r1$Real < 4] <- 0
pennystudy2r1$Real[pennystudy2r1$Real > 3 & pennystudy2r1$Real < 7] <- 1
pennystudy2r1$Real


#create veracity column (Real - Fake)
pennystudy2r1['veracity']=pennystudy2r1['Real'] - pennystudy2r1['Fake']

#successful screen1 test (result = 2)
pennystudy2r1['screen1']=pennystudy2r1['screen1_4'] + pennystudy2r1['screen1_7']

#successful screen2 test (result = 2)
pennystudy2r1['screen2']=pennystudy2r1['screen2_3'] + pennystudy2r1['screen2_5']

#successful screen3 test (result = 3)
pennystudy2r1['screen3'] = na_if(pennystudy2r1$screen3_2,1)
pennystudy2r1['screen3'] = na_if(pennystudy2r1$screen3,2)
pennystudy2r1['screen3'] = na_if(pennystudy2r1$screen3,4)
pennystudy2r1['screen3'] = na_if(pennystudy2r1$screen3,5)
#to check if screen 3 successful
mean(pennystudy2r1$screen3, na.rm = TRUE)

#replace 2 and 3 to 1
pennystudy2r1["screen1"][pennystudy2r1["screen1"] == 2] <- 1
pennystudy2r1["screen2"][pennystudy2r1["screen2"] == 2] <- 1
pennystudy2r1["screen3"][pennystudy2r1["screen3"] == 3] <- 1


```


## reproduction of results (interaction between headline veracity and treatment)
### without considering attention check
```{r, message=FALSE}
install.packages("sandwich") 
install.packages("stargazer")
install.packages("lmtest")
library(lmtest)
library(stargazer) 
library(sandwich)


lm1 <- lm(Discern ~ condition + veracity + veracity*condition, data = pennystudy2r1)
summary(lm1)

stargazer(lm1, type='text')

coeftest(lm1, vcovHC)

#z scored
scale(pennystudy2r1$Discern)


lm1 = lm(scale(pennystudy2r1$Discern) ~ condition, data = pennystudy2r1)
summary(lm1)



```




### reproduction of figure 2 without considering attention check


```{r, message=FALSE}
pennystudy2r1$screen3_2

library(ggplot2)

pennystudy2plot1 <- pennystudy2r1 %>% 
  select (c(1, 2, 3))


library(reshape2)

pennystudy2plot1 <- melt(pennystudy2plot1, id = 'condition')
head(pennystudy2plot1)

#Find out the sum for each type of news in different condition
p1 <- aggregate(value~condition+variable, data = pennystudy2plot1, FUN = sum)


ggplot(p1, aes(x = condition, y = value / 428, fill = variable)) + 
  geom_bar(stat = 'identity',position = 'dodge')


```





















